const domains = [
  "Hardware:Printed circuit boards",
  "Hardware:Communication hardware, interfaces and storage",
  "Hardware:Integrated circuits",
  "Hardware:VLSI design",
  "Hardware:Power and energy",
  "Hardware:Electronic design automation",
  "Hardware:Hardware validation",
  "Hardware:Hardware test",
  "Hardware:Robustness",
  "Hardware:Emerging technologies",
  "Computer systems organization:Architectures (Serial, Parallel, Distributed, Cloud, Edge)",
  "Computer systems organization:Special Purpose (Neural, reconfigurable, dataflow, quantum, molicular, optical)",
  "Computer systems organization:Embedded and cyber-physical systems (Sensor, Robotics, SoC)",
  "Computer systems organization:Real-time systems (OS, Language)",
  "Computer systems organization:Dependable and fault-tolerant systems (Reliability, Availability, Redundancy)",
  "Networks:architectures",
  "Networks:protocols",
  "Networks:Network components",
  "Networks:algorithms",
  "Networks:performance evaluation",
  "Networks:security, reliability",
  "Networks:services (Naming, Cloud, Location, Programmable)",
  "Networks:types (NoC, SAN, Data center, Sensor and Mobile network, Overlay, Adhoc, Wireless)",
  "Software engineering:Software organization (Middleware, OS, Architecture)",
  "Software engineering:Languages, Models, Tools",
  "Software engineering:Software Generation, Maintenance",
  "Software engineering:Testing, Model Checking, Validation and Verification",
  "Theory of computation:Models of computation",
  "Theory of computation:Formal languages and automata theory",
  "Theory of computation:Computational complexity and cryptography",
  "Theory of computation:Logic",
  "Theory of computation:Design and analysis of algorithms (Graph, Approximate, Optimization, Parallel and Distributed)",
  "Theory of computation:Randomness, geometry and discrete structures",
  "Theory of computation:Theory and algorithms for application domains (ML Theory, Game Theory, Database theory)",
  "Theory of computation:Semantics and reasoning",
  "Mathematics of computing:Discrete mathematics",
  "Mathematics of computing:Probability and statistics",
  "Mathematics of computing:Mathematical software",
  "Mathematics of computing:Information theory",
  "Mathematics of computing:Mathematical analysis",
  "Mathematics of computing:Continuous mathematics",
  "Information systems:Data management systems",
  "Information systems:Information storage systems",
  "Information systems:Information systems applications (Social Computing, Spatio-temporal, DSS, Data mining, Advertising)",
  "Information systems:WWW (Search, Advertising, Web mining, EComm, Social Network, Web services)",
  "Information systems:Information retrieval",
  "Security and privacy:Cryptography",
  "Security and privacy:Formal methods and theory of security",
  "Security and privacy:Security services",
  "Security and privacy:Intrusion/anomaly detection and malware mitigation",
  "Security and privacy:Security in hardware",
  "Security and privacy:Systems security",
  "Security and privacy:Network security",
  "Security and privacy:Database and storage security",
  "Security and privacy:Software and application security",
  "Security and privacy:Human and societal aspects of security and privacy",
  "Human-centered computing:Human computer interaction (HCI)",
  "Human-centered computing:Interaction design",
  "Human-centered computing:Collaborative and social computing",
  "Human-centered computing:Ubiquitous and mobile computing",
  "Human-centered computing:Data Visualization",
  "Human-centered computing:Accessibility",
  "Computing methodologies:Symbolic and algebraic manipulation",
  "Computing methodologies:Parallel and concurrent computing",
  "Computing methodologies:Artificial intelligence (NLP, Knowledge representation, Planning, Search, Distributed AI, Computer Vision)",
  "Computing methodologies:Machine learning (Learning Paradigm, Setting, Approaches & Algorithms)",
  "Computing methodologies:Modeling and simulation",
  "Computing methodologies:Computer graphics",
  "Computing methodologies:Distributed computing",
  "Applied computing:Electronic commerce",
  "Applied computing:Enterprise computing (BPM, EIS, SOA, IT architecture and governance)",
  "Applied computing:Physical sciences and engineering",
  "Applied computing:Life and medical sciences",
  "Applied computing:Law, social and behavioral sciences",
  "Applied computing:Computer forensics",
  "Applied computing:Arts and humanities",
  "Applied computing:Other domains (digital library, military, agriculture, government)",
  "Applied computing:Operations research",
  "Applied computing:Education",
  "Applied computing:Document management and text processing",
  "Social and professional topics:Professional topics",
  "Social and professional topics:Computing / technology policy",
  "Social and professional topics:User characteristics",
];
export default domains;
